services:
  app:
    container_name: paylinq-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${POSTGRES_PRISMA_URL}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
      # Very important: don't override Prisma client
      - /app/node_modules/.prisma
      - /app/node_modules/@prisma/client
    
  ngrok:
    container_name: paylinq-webhook
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http app:3000
    depends_on:
      - app

networks:
  default:
    name: paylinq-network